{"name": "Проверка наличия ошибки создания пользователя, который уже зарегистрирован", "status": "passed", "start": 1732652684791, "stop": 1732652685453, "uuid": "0606f414-7f1a-4181-bc1b-24ef9b7b0d2d", "historyId": "0a831b4f53ff330418b77e214948b13b", "testCaseId": "0a831b4f53ff330418b77e214948b13b", "fullName": "tests.test_create_user.TestCreateUser#test_cant_create_same_user", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_user"}, {"name": "subSuite", "value": "TestCreateUser"}, {"name": "host", "value": "home"}, {"name": "thread", "value": "14227-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_user"}]}