{"name": "Проверка ошибки логина несуществующего пользователя", "status": "passed", "start": 1732652701742, "stop": 1732652702358, "uuid": "5284d2ea-4b01-4099-a303-d2eed1897732", "historyId": "a9e993ee895fc247f853e34fd8b42f16", "testCaseId": "a9e993ee895fc247f853e34fd8b42f16", "fullName": "tests.test_user_login.TestUserLogin#test_cant_login_as_wrong_user", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_login"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "home"}, {"name": "thread", "value": "14227-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_login"}]}